name: Publish

on:
  push:
    tags:
      - v*

jobs:
  images:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        base-image:
          - quay.io/kairos/core-opensuse-arm-rpi:v2.0.3
          - quay.io/kairos/core-opensuse-leap-arm-generic:v2.0.3
        k3s-version:
          - v1.25.2+k3s1
          - v1.25.0+k3s1
          - v1.24.6+k3s1
          - v1.24.4+k3s1
          - v1.23.12+k3s1
          - v1.23.10+k3s1
          - v1.22.15+k3s1
          - v1.22.13+k3s1
    env:
      REGISTRY: quay.io
      REGISTRY_USER: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@master
      - uses: sigstore/cosign-installer@main
      - uses: docker/setup-buildx-action@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin $REGISTRY
      - run: env | grep ACTIONS_ID_TOKEN_REQUEST > .env
      - run: env | grep REGISTRY >> .env
      - run: earthly --ci --push +docker-arm64-platforms --K3S_VERSION=${{ matrix.k3s-version }} --BASE_IMAGE=${{ matrix.base-image }}
      - run: earthly --ci +cosign-arm64-platforms --K3S_VERSION=${{ matrix.k3s-version }} --BASE_IMAGE=${{ matrix.base-image }}

